#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

models: ["*"]
table_or_view: 'table'
